import React from "react";
import "./Home.css";
import { Link } from "react-router-dom";

function Home(props) {
  return (
    <>
<<<<<<< HEAD
      <div className="home my-5 me-4 d-flex flex-column">
        <div className="d-flex">

          <section
            className="container d-flex flex-column align-items-center ms-3 p-3"
            id="home"
          >
            <h3 style={{ fontSize: "2rem" }}>
              <strong>
                Give freely, you may never know whom that gift will help.
              </strong>
            </h3>
            <p>
              Your one donation can save or improve the life of up to three
              people, so be the lifesaver..
            </p>

=======
      <div className="home d-flex flex-column">
        <section className="section-1 p-5 mb-2 d-flex">
          <div
            className="section-1-text d-flex flex-column align-items-center me-3"
            id="home"
          >
            <h3>
              “Every person can make a difference, and every person should try.”
            </h3>
            <h5 className="ms-auto">- John F. Kennedy</h5>
            <p>
              Your one donation can save or improve the life of up to three
              people, so be the lifesaver..
            </p>

>>>>>>> 7bbe315cbe811132c998c80e493c87d520cdfccc
            <h1>
              <strong style={{ fontSize: "3rem" }}>With..</strong>
            </h1>
            <img
              src={props.logo}
              alt="Blood Warriors"
              style={{ width: "250px" }}
            />
<<<<<<< HEAD
            <Link to="/" className="btn btn-lg">
              Donate Now
            </Link>
          </section>
          <div
            className="asset-1 d-flex align-items-center p-3"
          >
            <img
              src="/asset1.jpg"
              alt="asset"
              style={{ width: "700px", height: "auto" }}
            />
          </div>
        </div>
=======
            <Link to="/donate" className="btn btn-lg mb-4">
              Donate Now
            </Link>
          </div>
          <div className="asset-1 d-flex align-items-center">
            <img
              src="assets/asset1.jpg"
              alt="asset"
            />
          </div>
        </section>
        <section className="section-2 d-flex my-2 mx-4">
          <img
            src="assets/volunteerBg.png"
            alt="volunteerBG"
          />
          <div className="section-2-text d-flex flex-column align-items-center justify-content-center ms-auto p-4">
            <h3>
              “Everybody can be great. Because anybody can serve. You don’t have
              to have a college degree to serve. You don’t have to make your
              subject and your verb agree to serve. You don’t have to know the
              second theory of thermodynamics in physics to serve. You only need
              a heart full of grace. A soul generated by love.”
            </h3>
            <h5 className="ms-auto">- Martin Luther King, Jr.</h5>
            <Link to="/donate" className="btn btn-lg">
              Become a Volunteer
            </Link>
          </div>
        </section>
        <section className="section-3 d-flex m-4">
          <div className="section-3-text d-flex flex-column align-items-center p-4">
            <h3>
              “One of the marvelous things about community is that it enables us
              to welcome and help people in a way we couldn’t as individuals.
              When we pool our strength and share the work and responsibility,
              we can welcome many people, even those in deep distress, and
              perhaps help them find self-confidence and inner healing.”
            </h3>
            <h5 className="me-auto">– Jean Vanier</h5>
            <p className="my-3">
              Make your own community on the{" "}
              <strong>Blood Warriors India</strong> platform.
            </p>
            <Link to="/donate" className="btn btn-lg">
              Register Your Community
            </Link>
          </div>
        </section>
        <section className="section-4 d-flex my-2 p-4">
          <img src="/assets/sponsorsBg.png" alt="sponsorsBG" />
          <div className="section-4-text d-flex flex-column align-items-center p-4">
            <h3>
              "We know only too well that what we are doing is nothing more than
              a drop in the ocean. But if the drop were not there, the ocean
              would be missing something."
            </h3>
            <h5 className="ms-auto">- Mother Teresa</h5>
            <p className="my-3">
              Become a sponsor and serve by giving some gifts from yourside to
              them, who are contributing their precious time, effort and part of
              their life
              <strong> so that someone can actually have a life.</strong>
            </p>
            <div>
              <Link to="/donate" className="btn btn-lg">
                Become a Sponser
              </Link>
            </div>
          </div>
        </section>
>>>>>>> 7bbe315cbe811132c998c80e493c87d520cdfccc
      </div>
    </>
  );
}

export default Home;
